# Generated by Django 6.0.6 on 2026-06-08 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Kategori Adı')),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Emoji')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sira', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True, verbose_name='Masa Numarası')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Dolu mu?')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR Kodu')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Toplam Tutar (₺)')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('hazirlaniyor', 'Hazırlanıyor'), ('hazir', 'Hazır'), ('odendi', 'Ödendi')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Sipariş Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='cafe.masa', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat (₺)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Görsel')),
                ('stock_status', models.BooleanField(default=True, verbose_name='Stokta Var')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='cafe.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category__sira', 'sira', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Birim Fiyat (₺)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='cafe.siparis', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
    ]
