# Generated by Django 5.2.7 on 2026-06-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödendi mi?'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('hazirlaniyor', 'Hazırlanıyor'), ('hazir', 'Hazır'), ('teslim', 'Teslim Edildi')], default='beklemede', max_length=20, verbose_name='Mutfak Durumu'),
        ),
    ]
