# Generated by Django 5.2.7 on 2026-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_siparis_is_paid_siparis_paid_at_alter_siparis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok Adedi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Görünüm Sırası'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='stock_status',
            field=models.BooleanField(default=True, verbose_name='Satışta (menüde aktif)'),
        ),
    ]
